-- PR6 round 2 (Devin, 2026-10-02, via orchestrator): the trial seat cap is
-- 35, not unlimited (reversing the first PR6 pass) -- and at trial end, an
-- over-cap unpaid firm no longer just "freezes in place." The admin picks
-- which up-to-3 staff stay active; the rest are PAUSED (no reminders,
-- nothing deleted, restored instantly on upgrade or on choosing differently).
--
-- subscribers.paused_at: nullable. NULL = this staff member is active (gets
-- reminders, same as today). Non-NULL = paused -- set and cleared ONLY by
-- store.ts's reconcileRosterPauseState()/setRosterActivePicks(), never by
-- the normal signup/add-staff path. allConfirmedActive() (the reminder
-- cron's own query) must filter on this -- see that function's own comment.
--
-- firms.active_staff_choice_at: nullable. NULL = the admin has never made
-- an explicit pick; the pause reconciliation applies its own default (the
-- earliest-added N stay active) and may keep re-applying it as the roster
-- changes. Non-NULL = the admin has explicitly chosen at least once;
-- reconciliation then leaves paused_at exactly as that choice set it and
-- never silently reverts to the earliest-N default again -- it does NOT
-- re-validate the chosen set against a roster that grows further past it
-- (AuditLab PR6-I, LOW, 2026-10-02: this comment used to describe a
-- dynamic re-shrinking behaviour the code never implemented; corrected to
-- match store.ts's reconcileRosterPauseState(), the actual, tested
-- behaviour). Only store.setRosterActivePicks() -- a fresh explicit
-- choice -- changes paused_at once this field is set. Also only ever set
-- while firmRosterOverCapUnpaidPostTrial() is true (AuditLab PR6-H,
-- MEDIUM): the active-picks handler refuses a pick made while the roster
-- is still mid-trial, under cap, or already paid, so this field can never
-- record a choice that wasn't meaningful yet.
ALTER TABLE subscribers ADD COLUMN paused_at TEXT;
ALTER TABLE firms ADD COLUMN active_staff_choice_at TEXT;
